<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="card plco-membership-card-delete small red lighten-2">
	<div class="card-content ">
		<span class="card-title white-text"><strong><?php _e( 'Are you sure you want to delete Membership Level "', PLCOM_Const::T ) ?><#= model.get("membership_name") #>" ?</strong></span>

	</div>
	<div class="card-action right">
		<div class="row">

			<div class="col s6">
                <a href="javascript:void(0)" class="btn red lighten-1 plco-yes white-text "><?php _e( 'Yes', PLCOM_Const::T ) ?></a>
			</div>
            <div class="col s6">
                <a href="javascript:void(0)" class="btn red lighten-1 plco-no white-text right"><?php _e( 'No', PLCOM_Const::T ) ?></a>
            </div>
		</div>

	</div>
</div>