<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php _e( 'Payment Methods', PLCOM_Const::T ) ?> </h5>

<div class="row">
	<div class="col s8">
		<ul class="collection with-header plco-available-connections">
			<li class="collection-header"><h6><?php _e( 'Available Connections', PLCOM_Const::T ) ?></h6></li>
		</ul>
	</div>
</div>