<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php _e( 'Custom Registration Form Fields', PLCOM_Const::T ) ?></h5>

<div class="row">
	<div class="col s12">
		<ul class="plco-tab-settings-items"></ul>
	</div>
</div>

<div class="row">
	<div class=" col s8">
		<h6><?php _e( 'Custom Registration Form Fields are only available with the PRO version of this plugin. In order to have access to the Registraion Form Builder features get the PRO version at ', PLCOM_Const::T ) ?>
            <a href="https://pluginscorner.com" target="_blank">https://pluginscorner.com</a></h6>
    </div>
</div>
