<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php _e( 'Roles', PLCOM_Const::T ) ?> </h5>

<div class="row">
	<div class="col s8">
		<ul class="collection with-header plco-roles">
			<li class="collection-header"><h6><?php _e( 'Roles', PLCOM_Const::T ) ?></h6></li>
		</ul>
	</div>
    <div class="col s8">
        <a href="#roles/add" class="btn green right waves-light plco-add-new-role"><?php _e( 'Add New Role', PLCOM_Const::T ) ?></a>
    </div>
</div>