<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="col s12">
    <div class="row">
        <div class="input-field col s6">
            <input placeholder=" <?php _e( 'Role Name', PLCOM_Const::T ) ?>" name="name"
                   id="plco-role-name" type="text" value="<#= model.get("name") #>" class="validate">
            <label for="plco-role-name"><?php _e( 'Role Name', PLCOM_Const::T ) ?></label>
        </div>
        <div class="input-field col s6">
            <input placeholder=" <?php _e( 'Role ID', PLCOM_Const::T ) ?>" name="ID"
                   id="plco-role-id" type="text" value="<#= model.get("ID") #>" class="validate" disabled>
            <label for="plco-role-id"><?php _e( 'Role ID', PLCOM_Const::T ) ?></label>
        </div>

        <div class="plco-capabilities-wrapper col s12"></div>


        <div class="row">
            <div class="col s12">
                <a href="javascript:void(0)" class="btn green waves-light right plco-set-role">
					<?php echo __( 'Save Role', PLCOM_Const::T ) ?>
                </a>
            </div>
        </div>
    </div>
</div>