<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php _e( 'Add Roles', PLCOM_Const::T ) ?></h5>

<div class="row">
	<div class="plco-add-role-content col s8"></div>
</div>
<div class="row">
	<div class="col s12">
		<a href="#roles" class="btn grey waves-light"><?php _e( 'Back to Roles', PLCOM_Const::T ) ?></a>
	</div>
</div>