<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php _e( 'Statistics', PLCOM_Const::T ) ?></h5>

<div class="row">
	<div class=" col s8">
		<h6><?php _e( 'Statistics are only available with the PRO version of this plugin. In order to have access to Statistics regarding the monthly sales, average user spending and much more get the PRO version at ', PLCOM_Const::T ) ?>
            <a href="https://pluginscorner.com" target="_blank">https://pluginscorner.com</a></h6>
    </div>
</div>
