<?php
/**
 * http://pluginscorner.com
 *
 * @package plco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="col s12">
    <h5><?php _e( 'Plugins Corner Membership', PLCOM_Const::T ) ?></h5>
</div>
<div class="col s12 no-padding">
    <div class="col s12 plco-tab-items-wrapper">
        <ul class="plco-tab-items"></ul>
    </div>
</div>
<div class="col s12 plco-tabs-content">
    <div class="row">
        <div class="col s12 plco-tab-content"></div>
    </div>
</div>
