<?php
/**
 * PluginsCorner - https://pluginscorner.com.com
 *
 * @package pluco-membership
 */

use \PLCODashboard\admin\classes\PLCO_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="plco-material">
	<h3 class="modal-title cpt-pc-no-margin"><#= model.get('id') ? '<?php echo __( 'Edit Reply', PLCO_Const::T ) ?>' : '<?php echo __( 'Add a Reply', PLCO_Const::T ) ?>' #></h3>
	<div class="plco-modal-content">
		<div class="row">
			<div class="col s12">
				<label><?php echo __( 'Message', PLCO_Const::T ) ?></label>
				<textarea id="plco-reply-content" name="content" rows="30"></textarea>
			</div>
		</div>
	</div>

	<div class="plco-modal-footer">
		<div class="row">
			<div class="col s6">
				<a href="javascript:void(0)" class="btn grey waves-light left modal-close">
					<?php echo __( 'Cancel', PLCO_Const::T ) ?>
				</a>
			</div>
			<div class="col s6">
				<a href="javascript:void(0)" class="btn green waves-light right plco-add-reply">
					<#= model.get('id') ? '<?php echo __( 'Edit Reply', PLCO_Const::T ) ?>' : '<?php echo __( 'Reply', PLCO_Const::T ) ?>' #>
				</a>
			</div>
		</div>
	</div>
</div>


