<?php
/**
 * PluginsCorner - https://pluginscorner.com.com
 *
 * @package pluco-membership
 */

use \PLCODashboard\admin\classes\PLCO_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="plco-material">
	<h3 class="modal-title"><?php echo __( 'Disconnect account', PLCO_Const::T ) ?></h3>

	<div class="modal-content">
		<h6 class=""><?php _e( 'Are you sure you want disconnect your account ? ', PLCO_Const::T ) ?></h6>
	</div>
	<div class="modal-footer">
		<div class="row">
			<div class="col s6">
				<a href="javascript:void(0)" class="btn waves-light left grey modal-close">
					<?php echo __( 'No', PLCO_Const::T ) ?>
				</a>
			</div>
			<div class="col s6">
				<a href="javascript:void(0)" class="btn waves-light right green plco-yes">
					<?php echo __( 'Yes', PLCO_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
