<?php
/**
 * http://pluginscorner.com
 *
 * @package pluco-membership
 */

use \PLCOMembership\admin\classes\PLCOM_Const;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="plco-material">
	<h3 class="modal-title cpt-pc-no-margin"><?php echo __( 'Protect Post', PLCOM_Const::T ) ?></h3>
	<div class="plco-modal-step">
		<div class="modal-content">
			<h6 class=""><?php _e( 'Select or create membership levels which protect this post:', PLCOM_Const::T ) ?></h6>
			<br/>
			<div class="row plco-protect-post-wrapper"></div>
			<br/>
			<br/>
			<div class="row">
				<div class="col s12 no-padding">
					<a href="javascript:void(0)" class="btn waves-light right green plco-modal-next-step">
						<?php echo __( 'Add New Membership Level', PLCOM_Const::T ) ?>
					</a>
				</div>
			</div>

		</div>
		<div class="modal-footer">
			<div class="row">
                <div class="col s6">
                    <a href="javascript:void(0)" class="btn waves-light left grey modal-close">
						<?php echo __( 'Close', PLCOM_Const::T ) ?>
                    </a>
                </div>
				<div class="col s6">
					<a href="javascript:void(0)" class="btn waves-light right green plco-save">
						<?php echo __( 'Save', PLCOM_Const::T ) ?>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="plco-modal-step">
		<div class="modal-content">
			<h6 class=""><?php _e( 'Add a new Membership Level:', PLCOM_Const::T ) ?></h6>
			<br/>

			<div class="row">
				<div class="plco-add-membership-level-content col s12"></div>
			</div>

		</div>
		<div class="modal-footer">
			<div class="row">
				<div class="col s12">
					<a href="javascript:void(0)" class="btn waves-light left grey plco-modal-prev-step">
						<?php echo __( 'Back', PLCOM_Const::T ) ?>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
